name: Calculator
description: A simple console calculator in Dart/flutter by Bruno Magno
version: 1.0.0
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/calculator.png"
  remove_alpha_ios: true
  web:
    generate: true

flutter:
  uses-material-design: true
